### ISSUE TITLE
运行demo报错.

### ISSUE THREAD

**Issue by DolphinsLoveCats** [scfhao/SODownloader#1]
报错信息如下 : 
![image](https://cloud.githubusercontent.com/assets/16606029/24795212/25a3c82c-1bbb-11e7-9da3-99e132425e24.png)
猜测你的方法被自己替换但是没有在demo内实现...

**Comment by scfhao** [comment]
你好，很抱歉过了这么久才回复，你7天前就提交了Issue，但我昨天才收到提醒邮件。
Demo报错的原因如你所说，我在SODownloader的初始化方法中增加了timeout参数，但在Demo的调用处没做修改，现已修正，感谢提示。
欢迎使用SODownloader！
