### ISSUE TITLE
发现在任务下载的时候，如果暂停任务再取消任务，那么下次再添加该任务的时候会加载上传下载的缓存

### ISSUE THREAD

**Issue by LinJiaXing1102** [scfhao/SODownloader#13]
原因是当任务暂停住的时候，取消该任务，没有清理掉已经下载好的部分。

SODownloader.m 
52行处 添加 `- (NSString *)resumePathForItem:(id<SODownloadItem>)item;`
306行处 添加 
```objc
BOOL res = [[NSFileManager defaultManager] removeItemAtPath:[self resumePathForItem:item] error:nil];
NSLog(@"%@", res ? @"沙盒删除成功" : @"沙盒删除失败");
```

**Comment by scfhao** [comment]
你好，目前的代码在这种情况下确实不会删除 resumeData，已对这种情况进行[优化](https://github.com/scfhao/SODownloader/commit/277cafe583b784488182d71a11c4b7d693c811a4)

**Comment by LinJiaXing1102** [comment]
还有一个小问题，就是当一个任务处于暂停状态的时候，app重新启动，它的下载进度so_downloadProgress无法获取，直接拿的话是0，不知是否有改进的方法？

**Comment by scfhao** [comment]
试试把这个进度保存到数据库中，下次启动后从数据库读取这个值然后赋值给下载对象。

**Comment by LinJiaXing1102** [comment]
在下载的时候把进度存到数据库，这样的话即使是0.00001也会调用存储数据库一次，这样操作频率好像有点大呀

**Comment by scfhao** [comment]
程序退出的时候保存，可以不？或者是下载状态从下载中变成暂停的时候保存一下，都可以啊。

**Comment by LinJiaXing1102** [comment]
我试了下可以，在 `- (void)applicationWillTerminate:(UIApplication *)application` 中进行保存即可。

顺带还发现了，计算下载速度有一个小错误
把
`[NSString stringWithFormat:@"%.2f MB/s", speed / 1024 * 1024]`
改为
`[NSString stringWithFormat:@"%.2f MB/s", speed / 1024 / 1024]`

**Comment by scfhao** [comment]
好的，已经修改

**Comment by LinJiaXing1102** [comment]
emmm  大佬有研究过多任务异步上传 这个功能吗

**Comment by scfhao** [comment]
没做过，之前有个人仿照这个项目写了个uploader，不知道结果如何。
看到过文档上说上传和下载不太一样，如果上传文件可以后台，上传内存中的data不可以。

**Comment by LinJiaXing1102** [comment]
👌
