### ISSUE TITLE
Debug模式下报错,Release模式下没问题?

### ISSUE THREAD

**Issue by songyuyang0918** [scfhao/SODownloader#17]
Debug模式下报错:
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SWDGLoadMap 0x283072c70> valueForUndefinedKey:]: this class is not key value coding-compliant for the key fractionCompleted.'

Release模式完美运行, 为什么呢? 求解作者大大~

**Comment by scfhao** [comment]
可以再多提供点信息吗？用的真机？哪个iOS版本

**Comment by songyuyang0918** [comment]
IOS12
Xcode10
真机是 iphone XS Max
<img width="646" alt="2018-10-16 3 17 19" src="https://user-images.githubusercontent.com/15685672/46998912-98750a80-d156-11e8-9003-40df556c1205.png">

我一开始使用的是cocopoads继承的
然后发现和demo里面的不是太一样, 我又按照demo里面的设置修改了一下相关的类

**Comment by songyuyang0918** [comment]
您的demo是没有问题的

**Comment by scfhao** [comment]
SWDGLoadMap 是你自己写的类了？

**Comment by songyuyang0918** [comment]
是的, 这是我自己的 model模型

**Comment by songyuyang0918** [comment]
我继承了 您的SODownloadItem类和协议..   
以及必须实现的方法
<img width="753" alt="2018-10-16 3 22 07" src="https://user-images.githubusercontent.com/15685672/46999107-497ba500-d157-11e8-97cf-5e49139ee6a3.png">

**Comment by scfhao** [comment]
fractionCompleted 是 NSProgress 类的属性，和 SODownloadItem 协议的 so_downloadProgress 这个属性有关，你可以检查一下对这个属性的 KVO。

**Comment by songyuyang0918** [comment]
<img width="960" alt="2018-10-16 3 33 02" src="https://user-images.githubusercontent.com/15685672/46999657-d7a45b00-d158-11e8-8668-03b432b67c71.png">
我在KVO的监听方法里 打了断点 但它没有走这里..

**Comment by scfhao** [comment]
你应该监听这个 keypath：SODownloadItemProgressObserveKeyPath

**Comment by songyuyang0918** [comment]
<img width="1497" alt="2018-10-16 3 38 02" src="https://user-images.githubusercontent.com/15685672/46999919-9b252f00-d159-11e8-98d9-ccbc7a73d051.png">
是的,您说的没错.
我想我是按照您说的属性监听的, 没到这个断点就崩了

**Comment by scfhao** [comment]
加我QQ 2945214949 吧，我看一下
