### ISSUE TITLE
downloadingArray会添加多个相同对象

### ISSUE THREAD

**Issue by ipad4** [scfhao/SODownloader#18]
SODownloadStateWait状态时会插入到downloadingArray中，变为SODownloadStateLoading时，还会再插入downloadingArray中。再问一下为何将NSMutableIndexSet注释掉换成了NSMutableArray来保存任务？

**Comment by scfhao** [comment]
只要不是下载完成状态的对象，会一直在downloadingArray数组中。
在Array中也会判断是否包含重复的对象，参考[WiKi](https://github.com/scfhao/SODownloader/wiki/%E4%BF%9D%E8%AF%81%E4%B8%8B%E8%BD%BD%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%94%AF%E4%B8%80%E6%80%A7)
