### ISSUE TITLE
自签名证书

### ISSUE THREAD

**Issue by DabbyCHEN** [scfhao/SODownloader#19]
您好：
	我想在项目中使用您的SODownloader，但遇到了一个问题：

	项目使用了自签名证书，下载地址是https协议的。
	除了下载，项目其他https请求也是用的AFNetworking：

	let sessionManager = AFHTTPSessionManager(baseURL: url)
        sessionManager.securityPolicy = SHttp.securityPolicy()

    通过配置SecurityPolicy来验证自签名证书，但是如果采用initWithSessionConfiguration来初始化AFHTTPSessionManager，正如SODownloader这样，程序会崩溃：

Terminating app due to uncaught exception 'Invalid Security Policy', reason: 'A security policy configured with `AFSSLPinningModePublicKey` can only be applied on a manager with a secure base URL (i.e. https)'

    所以改为用baseURL来初始化AFHTTPSessionManager，这样就可以运行了。

    同样，在SODownloader中，我修改了SODownloader的初始化方法initWithIdentifier，传入SecurityPolicy也会出现这个错误。但是没有办法在初始化SODownloader单例时传入URL。所以想请教您有没有解决思路呢？

感谢！
期待您的回信。

Dabby
2019.5.16

**Comment by scfhao** [comment]
你好：

AFNetworking 中在设置 Security Policy 时验证了 AFHTTPSessionManager 的 baseURL 的 scheme 是否为 https，如果不是就抛出了上述的异常。

SODownloader 是基于 AFNetworking 开发的，在 SODownloader 的 init 方法中有创建 AFHTTPSessionManager 对象的代码，你可以修改一下这个地方为 manager 传如 baseURL。

**Comment by DabbyCHEN** [comment]
你好：
        是的，我确实是修改了SODownloader的init方法来传入Security Policy。
        但是，这个SODownloader是单例初始化的，我每次下载的URL都是不同，那我传入第一个，或者任意一个https也可以吗？之后的下载任务也可以进行吗？

**Comment by scfhao** [comment]
是的，从 AFNetworking 的源码来看可以这么做。

**Comment by DabbyCHEN** [comment]
非常感谢！
