### ISSUE TITLE
关于baseOnAF2文件

### ISSUE THREAD

**Issue by DolphinsLoveCats** [scfhao/SODownloader#2]
您好:
很高兴您关闭了我上一次提交的issue
我在您的技术文档中看到您 对  AFNetworking 2.x 的支持做了相关的说明,不过我未找到您说的``` baseOnAF2 ```分支,您是不是已经取消了呢?还是我找错了? 
因为使用的项目基于  ``` AFNetworking 2.x ``` 开发的,换到3.0的话改动的会很多
希望您将其填入,谢谢.
非常感谢您能公开这个下载库,我希望在以后的使用中能更好的与您互动.

**Comment by scfhao** [comment]
你好，SODownloader 的`master`分支是基于 AFNetworking 3 的，由于我自己的项目中也是使用 AFNetworking 2 开发的，所以我又做了对 AFNetworking 2 的支持，放在`baseOnAF2`分支。但`baseOnAF2`只作为一个兼容的基础的使用，SODownloader（AFNetworking 3） 后面继续完善的功能也没有加到`baseOnAF2`。

你可以通过下面的 Git 命令找到`baseOnAF2`分支的代码：

```bash
// 1. 克隆 SODownloader 仓库。
$ git clone https://github.com/scfhao/SODownloader.git

// 2. 进入 SODownloader 目录
$ cd SODownloader

// 3. 检出 baseOnAF2 分支
$ git checkout -b baseOnAF2 origin/baseOnAF2
```
