### ISSUE TITLE
目前测试到一个问题，关于暂停后的临时文件处理

### ISSUE THREAD

**Issue by cooliean** [scfhao/SODownloader#4]
在任务继续后，读取了临时文件   [url.md5].download 文件
目前测试在任务完成后没有移除这个暂停缓存的文件。
这个文件目前不删除好像有问题，我的操作是这样的：
下载成功后，我就吧成功的文件删除了，以后继续下载，这样每次完成的文件都是有问题的。

**Comment by scfhao** [comment]
你好，周末被俗事缠身，抱歉现在才回复你。
我简单测试了一下：在Demo中的“示例（音乐列表）”中下载一个音乐文件。然后在“示例（已下载列表）”中删除下载，再回到“示例（音乐列表）”中下载同一个音乐文件，没有发现问题。
你可以参考一下Demo中的流程，如果是我没理解到你说的问题，请详细指出。

**Comment by 4533206** [comment]
这哥们曾经是个王者，后来说声算了

**Comment by scfhao** [comment]
感谢 @cooliean 的反馈，确实存在这样的问题。现增加了下面两个逻辑：
1. 从暂停状态继续下载后，删除 resumeData。
2. 使用 resumeData 继续下载时，判断了之前下载的`.tmp`文件是否存在。

问题已修复。
