### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by LoveCorner** [scfhao/SODownloader#6]
1.下载视频给的网址是在模型里面的#pragma mark - SODownloadItem必须实现的方法
-(NSURL *)so_downloadURL{
    NSSLog(@"%@",self.videoUrl);
    return [NSURL URLWithString:[NSString stringWithFormat:@“”]];
}这个方法里面赋值的吗 运行出来是空的，这个如何赋值才能下载视频
3.我要想要在下载视频成功的时候保存到数据库这个过程 你这个下载要先给模型，有没有给出视频的链接像AF那样就可以下载了 然后拿到视频的数据，最后把模型以及视频的数据保存到数据库

**Comment by scfhao** [comment]
1. 如果你有模型类的话，在模型类的so_downloadURL方法中返回视频的下载地址就可以了，可以参考Demo中的SOMusic类。
2. SODownloader提供了一个回调，每个文件下载完成后这个这个回调就会对应的被调用一次，该回调的参数就是要下载的模型对象，你可以在这个回调里把已下载的视频文件移动到你要保存的目录，也可以在这个回调里把已下载的视频数据保存到数据库哦。可以参考Demo中的SODownloader+MusicDownloader.m文件。
