### ISSUE TITLE
demo里暂停下载后重新开启，下载进度清零了

### ISSUE THREAD

**Issue by gdfyj90** [scfhao/SODownloader#9]
我看前面有人提了个issue说可以断点下载，那进度不是应该从原来已经下好的进度开始吗？

**Comment by scfhao** [comment]
先说一下 NSURLSession 提供的断点续传技术：

当下载的数据传输中产生错误或当调用`cancelByProducingResumeData:`方法时，NSURLSessionDownloadDelegate 对象和完成回调会得到一个 NSError 对象。如果传输可以继续进行，这个 error 对象的 userInfo 字典中会抱憾 NSURLSessionDownloadTaskResumeData。然后就可以将这个值传给 NSURLSession 对象的`downloadTaskWithResumeData:`或`downloadTaskWithResumeData:completionHandler:`方法来恢复下载传输。

在这个过程中其实有两部分数据：

1. NSURLSession 产生的一个 resumeData，这其实是个字典，里面保存了一些下载任务的信息。
2. 另一个就是tempData，这就是那个下载了一半的文件，这个文件的位置或名称在 resumeData 中可以获取到。

开始下载时，当 SODownloader 可以找到当前下载任务的这两部分数据时，SODownloader 就可以并且会从之前的进度继续下载。

找不到 resumeData 或 tempData 的情况：
1. resumeData 在暂停下载、应用停止运行等情况下会自动保存，但在一些极端情况比如手机关机等无法保存。
2. resumeData 的规格也一直在变，在 iOS 7 时，resumeData 字典的版本是 1，而现在 iOS 11 中 resumeData 字典的版本已经是 4，如果 resumeData 规格变化，SODownloader 未能更新的情况下，SODownloader 可能会无法找到 tempData 的位置。
3. resumeData 和 tempData 两部分数据都存储在沙盒的`tmp/`目录下，所以这两个文件在一些情况下也存在被系统删除的可能。

**Comment by scfhao** [comment]
Demo 已更新
